config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'User'
  devise_for :technicians, class_name: 'Technician'
  resources :ads
  root 'pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.technician?
      can :create, Ad
      can :read, Ad
      can [:update, :destroy], Ad, user_id: user.id
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ActiveRecord::Base
	belongs_to :user
end

app/models/technician.rb
class Technician < User
	before_save :default_role

	def default_role
		self.role ||= 2
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :technicians
  has_one :ad

  enum role: [:guest, :user, :technician, :admin]

  before_save :default_role

  def default_role
  	self.role ||= 1
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  # before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    # @ad = Ad.new(ad_params)
    @ad = current_user.create_ad(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) do |u|
  		u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone, :rfc)
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<h1>Listing Ads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.title %></td>
        <td><%= ad.description %></td>
        <td><%= link_to 'Show', ad %></td>
        <td><%= link_to 'Edit', edit_ad_path(ad) %></td>
        <td><%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwoModels</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h2>Home Page</h2>

<% if user_signed_in? %>
	<%= current_user.email %>
	<br>
	<%= current_user.role %>
<% end %>

<h3>Sign Up Technicians</h3>
<p><%= link_to "Sign Up", new_technician_registration_path %></p>

<h3>Sign Up Members</h3>
<p><%= link_to "Sign Up", new_user_registration_path %></p>

<% if user_signed_in? %>
  <p>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </p>
<% else %>
  <p>
  <%= link_to('Login', new_user_session_path)  %>
  </p>
<% end %>

<% if can? :create, Ad %>
	<%= link_to "New Ad", new_ad_path %>
<% end %>